# Generated by Django 3.2.6 on 2021-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.BigIntegerField(null=True),
        ),
    ]
