# Generated by Django 3.2.6 on 2021-08-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, null=True, verbose_name='category')),
                ('cat_img', models.FileField(null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Jewellery_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, null=True, verbose_name='Jewellery Type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200, null=True, verbose_name='Product Name')),
                ('gem_stone', models.CharField(max_length=200, null=True, verbose_name='Gem Stone')),
                ('brand', models.CharField(max_length=200, null=True, verbose_name='Brand')),
                ('metal', models.CharField(choices=[('Gold', 'Gold')], default=('Gold', 'Gold'), max_length=200, verbose_name='Metal')),
                ('metal_color', models.CharField(choices=[('Yellow', 'Yellow')], default=('Yellow', 'Yellow'), max_length=200, verbose_name='Metal Color')),
                ('height', models.CharField(max_length=200, null=True, verbose_name='Height')),
                ('purity', models.CharField(max_length=200, null=True, verbose_name='Purity')),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Other', 'Other')], default=('Men', 'Men'), max_length=100, verbose_name='Gender')),
                ('occasion', models.CharField(choices=[('Work Wear', 'Work Wear'), ('Office Wear', 'Office Wear')], max_length=200, verbose_name='Occasion')),
                ('width', models.CharField(max_length=200, null=True, verbose_name='Width')),
                ('gross_weight', models.CharField(max_length=200, null=True, verbose_name='Gross Weight')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Price')),
                ('offer', models.DecimalField(decimal_places=4, default=0.0, max_digits=15, verbose_name='Offer Price')),
                ('featured', models.BooleanField(default=False, null=True, verbose_name='Featured')),
                ('pro_img', models.FileField(upload_to='', verbose_name='Product Image')),
                ('extra_desc', models.TextField(null=True, verbose_name='Description')),
                ('pro_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_cat', to='product.category', verbose_name='Category')),
                ('pro_jw_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_jw_type', to='product.jewellery_type', verbose_name='Jewellery Type')),
            ],
        ),
    ]
