# Generated by Django 3.2.6 on 2021-08-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210819_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='metal_color',
        ),
        migrations.CreateModel(
            name='Product_Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_color', models.CharField(choices=[('Yellow', 'Yellow')], default=('Yellow', 'Yellow'), max_length=50, verbose_name='Metal Color')),
                ('color_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
