# Generated by Django 3.2.6 on 2021-08-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210819_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_color',
            name='metal_color',
            field=models.CharField(choices=[('yellow', 'yellow')], default=('yellow', 'yellow'), max_length=50, verbose_name='Metal Color'),
        ),
    ]
