# Generated by Django 3.2.6 on 2021-08-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210819_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_color',
            name='metal_color',
            field=models.CharField(choices=[('yellow', 'yellow'), ('red', 'red')], default=('yellow', 'yellow'), max_length=50, verbose_name='Metal Color'),
        ),
    ]
