# Generated by Django 3.2.6 on 2021-08-29 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500, null=True)),
                ('ammount', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=100)),
                ('billing_postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('order_address', models.CharField(blank=True, max_length=500, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('chekout_color', models.CharField(max_length=50, null=True)),
                ('chekout_quantity', models.IntegerField(null=True)),
                ('order_status', models.CharField(blank=True, choices=[('Prepare To Dispatch', 'Prepare To Dispatch'), ('Dispatch', 'Dispatch'), ('Received', 'Received')], default=('Prepare To Dispatch', 'Prepare To Dispatch'), max_length=50, null=True)),
                ('ord_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_product', models.CharField(max_length=500, null=True)),
                ('ord_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('history_user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_user_name', to=settings.AUTH_USER_MODEL)),
                ('order_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='History_Checkout', to='order.checkout')),
            ],
        ),
    ]
