# Generated by Django 3.2.6 on 2021-08-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_checkout_order_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='ord_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
